name: Build ISO
on: [workflow_call, workflow_dispatch]
  

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: thevakhovske/holoiso:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Sanity check, if we are on SteamOS environment
        run: |
          cat /etc/os-release          
      
      - name: Install ArchISO
        run: |
          pacman -Sy
          pacman --noconfirm -S git archiso

      - name: Build ISO File
        run: |
          mkarchiso -v .
          find out/

      - uses: actions/upload-artifact@v2
        with:
          name: holoiso
          path: out/*.iso

      - uses: svenstaro/upload-release-action@v2
        with:
          file: out/*.iso
          overwrite: true
